[package]
name = "mdbook-blox"
version = "0.1.0"
edition = "2024"
license = "MIT"
keywords = ["mdbook", "markdown"]
repository = "https://github.com/wpmg/mdbook-blox"
authors = ["Wilmer Prentius <wilmer.prentius@slu.se>"]
description = "A preprocessor for mdbook to add figures and admonishment-like blox"

[dependencies]
anyhow = "1.0.100"
clap = {version = "4.5.53", default-features = false, features = ["std", "derive"]}
hex_color = {version = "3.0.0", default-features = false, features = ["serde"]}
mdbook-preprocessor = {version = "0.5.1"}
pathdiff = "0.2.3"
regex = "1.12.2"
semver = "1.0.27"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
toml = {version = "0.9.8"}
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.20", features = ["env-filter"]}
uuid = {version = "1.18.1", features = ["v4"]}

[dev-dependencies]
pretty_assertions = "1.4.1"
